# 1. 登入
POST http://{{host}}/v1/user/login
Content-Type: application/json

{
  "username": "{{username}}",
  "password": "{{password}}"
}

> {%
  client.test('Login successfully', function() {
    client.assert(200 === response.status, 'Want 200, but got ' + response.status);
  });
  client.global.set('token',  'Bearer ' + response.body.data.token);
%}

###

# 2. 修改密码
PATCH http://{{host}}/v1/user/change-password
Content-Type: application/json
Authorization: {{token}}

{
  "password": "{{password}}",
  "newPassword": "123456"
}

> {%
  client.test('Change password successfully', function() {
    client.assert(200 === response.status, 'Want 200, but got ' + response.status);
  });
%}

###

# 3. 使用旧密码登入失败
POST http://{{host}}/v1/user/login
Content-Type: application/json

{
  "username": "{{username}}",
  "password": "{{password}}"
}

> {%
  client.test('Login with old password failed', function() {
    client.assert(4999 === response.body.code, 'Want 4999, but got ' + response.body.code);
  });
%}

###

# 4. 使用新密码登入成功
POST http://{{host}}/v1/user/login
Content-Type: application/json

{
  "username": "{{username}}",
  "password": "123456"
}

> {%
  client.test('Login with new password successfully', function() {
    client.assert(200 === response.status, 'Want 200, but got ' + response.status);
  });
  client.global.set('token',  'Bearer ' + response.body.data.token);
%}

###

# 5. 改回旧密码
PATCH http://{{host}}/v1/user/change-password
Content-Type: application/json
Authorization: {{token}}

{
  "password": "123456",
  "newPassword": "{{password}}"
}

> {%
  client.test('Reset password to old password successfully', function() {
    client.assert(200 === response.status, 'Want 200, but got ' + response.status);
  });
%}

###
