# 登入
POST http://{{host}}/v1/user/login
Content-Type: application/json

{
  "username": "{{adminUsername}}",
  "password": "{{adminPassword}}"
}

> {%
  client.test('Login successfully', function() {
    client.assert(200 === response.status, 'Want 200, but got ' + response.status);
  });
%}

###