// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag

package docs

import (
	"bytes"
	"encoding/json"
	"strings"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{.Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "MJ Ma",
            "url": "https://www.linkedin.com/in/mj-profile/",
            "email": "m.mjw.ma@gmail.com"
        },
        "license": {
            "name": "MIT",
            "url": "https://github.com/jwma/jump-jump/blob/master/LICENSE"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/config": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "获取系统配置信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "系统配置"
                ],
                "summary": "获取系统配置信息",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/GetConfigAPIResponseData"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "401": {
                        "description": ""
                    }
                }
            }
        },
        "/config/id-length": {
            "patch": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "更新短链接 ID 设置",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "系统配置"
                ],
                "summary": "更新短链接 ID 设置",
                "parameters": [
                    {
                        "description": "更新短链接 ID 设置请求",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/IdConfig"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/GetConfigAPIResponseData"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "401": {
                        "description": ""
                    }
                }
            }
        },
        "/config/landing-hosts": {
            "patch": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "更新落地页 Hosts",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "系统配置"
                ],
                "summary": "更新落地页 Hosts",
                "parameters": [
                    {
                        "description": "更新落地页 Hosts 请求",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/UpdateLandingHostsAPIRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/GetConfigAPIResponseData"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "401": {
                        "description": ""
                    }
                }
            }
        },
        "/config/short-link-404-handling": {
            "patch": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "更新短链接 404 设置",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "系统配置"
                ],
                "summary": "更新短链接 404 设置",
                "parameters": [
                    {
                        "description": "更新短链接 404 设置请求",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/ShortLinkNotFoundConfig"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/GetConfigAPIResponseData"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "401": {
                        "description": ""
                    }
                }
            }
        },
        "/short-link/": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "短链接列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "短链接"
                ],
                "summary": "短链接列表",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "页码",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "每页条数",
                        "name": "pageSize",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/ListShortLinksAPIResponseData"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "401": {
                        "description": ""
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "创建短链接",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "短链接"
                ],
                "summary": "创建短链接",
                "parameters": [
                    {
                        "description": "创建短链接请求",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/CreateShortLinkAPIRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/CreateShortLinkAPIResponseData"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "401": {
                        "description": ""
                    }
                }
            }
        },
        "/short-link/{id}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "获取系统配置信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "短链接"
                ],
                "summary": "获取指定 ID 短链接",
                "parameters": [
                    {
                        "type": "string",
                        "description": "短链接 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/GetShortLinkAPIResponseData"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "401": {
                        "description": ""
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "删除短链接",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "短链接"
                ],
                "summary": "删除短链接",
                "parameters": [
                    {
                        "type": "string",
                        "description": "短链接 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/Response"
                        }
                    },
                    "401": {
                        "description": ""
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "更新短链接",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "短链接"
                ],
                "summary": "更新短链接",
                "parameters": [
                    {
                        "type": "string",
                        "description": "短链接 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "更新短链接请求",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/UpdateShortLinkAPIRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/UpdateShortLinkAPIResponseData"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "401": {
                        "description": ""
                    }
                }
            }
        },
        "/short-link/{id}/data": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "可查询短链接某个日期范围内的访问数据",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "短链接"
                ],
                "summary": "短链接访问数据",
                "parameters": [
                    {
                        "type": "string",
                        "description": "短链接 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "开始日期 YYYY-mm-dd",
                        "name": "startDate",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "结束日期 YYYY-mm-dd",
                        "name": "endDate",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/ShortLinkDataAPIResponseData"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "401": {
                        "description": ""
                    }
                }
            }
        },
        "/user/change-password": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "修改账号密码",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "账号"
                ],
                "summary": "修改账号密码",
                "parameters": [
                    {
                        "description": "修改密码请求",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/ChangePasswordAPIRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/Response"
                        }
                    },
                    "401": {
                        "description": ""
                    }
                }
            }
        },
        "/user/info": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "获取账号信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "账号"
                ],
                "summary": "获取账号信息",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/GetUserInfoAPIResponseData"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "401": {
                        "description": ""
                    }
                }
            }
        },
        "/user/login": {
            "post": {
                "description": "账号密码登入",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "账号"
                ],
                "summary": "账号登入",
                "parameters": [
                    {
                        "description": "登入请求",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/LoginAPIRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/LoginAPIResponseData"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/user/logout": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "登出",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "账号"
                ],
                "summary": "登出",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/Response"
                        }
                    },
                    "401": {
                        "description": ""
                    }
                }
            }
        }
    },
    "definitions": {
        "ChangePasswordAPIRequest": {
            "type": "object",
            "properties": {
                "newPassword": {
                    "description": "新密码",
                    "type": "string"
                },
                "password": {
                    "description": "原密码",
                    "type": "string"
                }
            }
        },
        "CreateShortLinkAPIRequest": {
            "type": "object",
            "properties": {
                "description": {
                    "description": "描述",
                    "type": "string",
                    "example": "Jump Jump project"
                },
                "id": {
                    "description": "只有管理员可以在创建的时候指定 ID",
                    "type": "string",
                    "format": "string",
                    "example": "RANDOM_ID"
                },
                "idLength": {
                    "description": "短链接 ID 长度",
                    "type": "integer",
                    "format": "int",
                    "example": 4
                },
                "isEnable": {
                    "description": "是否启用",
                    "type": "boolean",
                    "format": "boolean",
                    "example": true
                },
                "url": {
                    "description": "目标链接",
                    "type": "string",
                    "example": "https://github.com/jwma/jump-jump"
                }
            }
        },
        "CreateShortLinkAPIResponseData": {
            "type": "object",
            "properties": {
                "shortLink": {
                    "$ref": "#/definitions/ShortLinkData"
                }
            }
        },
        "GetConfigAPIResponseData": {
            "type": "object",
            "properties": {
                "config": {
                    "$ref": "#/definitions/SystemConfig"
                }
            }
        },
        "GetShortLinkAPIResponseData": {
            "type": "object",
            "properties": {
                "shortLink": {
                    "$ref": "#/definitions/ShortLinkData"
                }
            }
        },
        "GetUserInfoAPIResponseData": {
            "type": "object",
            "properties": {
                "role": {
                    "description": "角色，1 普通用户 | 2 管理员",
                    "type": "integer",
                    "enum": [
                        1,
                        2
                    ],
                    "example": 1
                },
                "username": {
                    "description": "用户名",
                    "type": "string",
                    "example": "admin"
                }
            }
        },
        "IdConfig": {
            "type": "object",
            "properties": {
                "idLength": {
                    "description": "ID 长度",
                    "type": "integer",
                    "format": "int",
                    "example": 6
                },
                "idMaximumLength": {
                    "description": "最大 ID 长度",
                    "type": "integer",
                    "format": "int",
                    "example": 10
                },
                "idMinimumLength": {
                    "description": "最小 ID 长度",
                    "type": "integer",
                    "format": "int",
                    "example": 2
                }
            }
        },
        "ListShortLinksAPIResponseData": {
            "type": "object",
            "properties": {
                "shortLinks": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/ShortLinkData"
                    }
                },
                "total": {
                    "type": "integer",
                    "format": "10",
                    "example": 10
                }
            }
        },
        "LoginAPIRequest": {
            "type": "object",
            "required": [
                "password",
                "username"
            ],
            "properties": {
                "password": {
                    "description": "密码",
                    "type": "string",
                    "example": "your_password"
                },
                "username": {
                    "description": "用户名",
                    "type": "string",
                    "example": "your_username"
                }
            }
        },
        "LoginAPIResponseData": {
            "type": "object",
            "properties": {
                "token": {
                    "description": "json web token",
                    "type": "string",
                    "example": "xxx.xxx.xxx"
                }
            }
        },
        "RequestHistory": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "ip": {
                    "type": "string"
                },
                "time": {
                    "type": "string"
                },
                "ua": {
                    "type": "string"
                },
                "url": {
                    "description": "由于短链接的目标连接可能会被修改，可以在访问历史记录中记录一下当前的目标连接",
                    "type": "string"
                }
            }
        },
        "Response": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "format": "int",
                    "default": 0,
                    "example": 0
                },
                "data": {
                    "type": "object"
                },
                "msg": {
                    "type": "string",
                    "default": "ok",
                    "example": "ok"
                }
            }
        },
        "ShortLinkData": {
            "type": "object",
            "properties": {
                "createTime": {
                    "description": "创建时间",
                    "type": "string"
                },
                "createdBy": {
                    "description": "创建者",
                    "type": "string",
                    "format": "string",
                    "example": "admin"
                },
                "description": {
                    "description": "描述",
                    "type": "string",
                    "format": "string",
                    "example": "Jump Jump project"
                },
                "id": {
                    "type": "string",
                    "format": "string",
                    "example": "RANDOM_ID"
                },
                "isEnable": {
                    "description": "是否启用",
                    "type": "boolean",
                    "format": "boolean",
                    "example": true
                },
                "updateTime": {
                    "description": "最后更新时间",
                    "type": "string"
                },
                "url": {
                    "description": "目标链接",
                    "type": "string",
                    "format": "string",
                    "example": "https://github.com/jwma/jump-jump"
                }
            }
        },
        "ShortLinkDataAPIResponseData": {
            "type": "object",
            "properties": {
                "histories": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/RequestHistory"
                    }
                }
            }
        },
        "ShortLinkNotFoundConfig": {
            "type": "object",
            "required": [
                "mode",
                "value"
            ],
            "properties": {
                "mode": {
                    "description": "模式",
                    "type": "string",
                    "enum": [
                        "content",
                        "redirect"
                    ],
                    "example": "content"
                },
                "value": {
                    "description": "值",
                    "type": "string",
                    "example": "page not found"
                }
            }
        },
        "SystemConfig": {
            "type": "object",
            "properties": {
                "idConfig": {
                    "description": "ID 配置",
                    "$ref": "#/definitions/IdConfig"
                },
                "landingHosts": {
                    "description": "落地页 Host 列表",
                    "type": "array",
                    "format": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "https://a.com/",
                        "https://b.com/"
                    ]
                },
                "shortLinkNotFoundConfig": {
                    "description": "短链接 404 配置",
                    "$ref": "#/definitions/ShortLinkNotFoundConfig"
                }
            }
        },
        "UpdateLandingHostsAPIRequest": {
            "type": "object",
            "properties": {
                "hosts": {
                    "type": "array",
                    "format": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "https://a.com/",
                        "https://b.com/"
                    ]
                }
            }
        },
        "UpdateShortLinkAPIRequest": {
            "type": "object",
            "required": [
                "url"
            ],
            "properties": {
                "description": {
                    "description": "描述",
                    "type": "string",
                    "example": "Jump Jump project"
                },
                "isEnable": {
                    "description": "是否启用",
                    "type": "boolean",
                    "format": "boolean",
                    "example": true
                },
                "url": {
                    "description": "目标链接",
                    "type": "string",
                    "example": "https://github.com/jwma/jump-jump"
                }
            }
        },
        "UpdateShortLinkAPIResponseData": {
            "type": "object",
            "properties": {
                "shortLink": {
                    "$ref": "#/definitions/ShortLinkData"
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "",
	Host:        "",
	BasePath:    "",
	Schemes:     []string{},
	Title:       "",
	Description: "",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
